version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 5s
      retries: 10

  bot:
    build: .
    container_name: autotrade-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
      - ./logs:/app/logs
    command: ["/bin/bash", "-lc", "scripts/init_ollama.sh && python app.py"]

  reporter:
    build: .
    container_name: autotrade-reporter
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
    command: ["/bin/bash","-lc","./scripts/start_cron.sh"]

volumes:
  ollama:
